variable "zone" {}
variable "region" {}
variable "type" {}
variable "instance_name" {}
variable "instance_type" {}
variable "boot_disk_size" {}
variable "boot_disk_type" {}
variable "boot_disk_image" {}
variable "snapshot_name" {}
variable "extended_disk_size" {}
variable "extended_disk_type" {}
variable "extended_disk_name" {}
variable "firewall" {}
variable "ebs_optimized" {}
variable "ebs_encrypted" {}
variable "ssh_user" {}
variable "ssh_public_keys" {}
variable "subnet_id" {}
