---
- name: Check if variable is specified
  fail:
    msg: "Path where secrets store should be defined with using tag `sign`. -e path=/path/to/secrets"
  failed_when: path is not defined
  when: "'chill' in ansible_run_tags"

- name: TX staking.chill
  command:
    argv:
    - "/usr/bin/node"
    - "../scripts/substrate_tx/chill.js"
    - "{{ relay_chain }}"
    - "{{ public_node_ws_url }}"
    - "{{ validators[inventory_hostname]['controller'] }}"
    - "{{ path }}"
  when: validators[inventory_hostname]['controller'] is defined
  register: sign_result
  delegate_to: localhost
  become: no

- name: Set body for posting to slack
  set_fact:
    body: {"text":"{{ inventory_hostname }}(`{{ validators[inventory_hostname]['controller'] }}`):\n\nValidator chill\n\nTX: {{ sign_result['stdout'] }}"}
  when: sign_result['stdout'] is defined

- name: Post to slack
  uri:
    url: "{{ node_slack_channel }}"
    method: POST
    body_format: json
    return_content: yes
    body: "{{ body }}"
  when: body is defined
  register: result
  ignore_errors: yes
  delegate_to: localhost
  become: no

- name: Print results
  debug:
    msg: "TX: {{ sign_result }}"
  when: sign_result is defined
