---
- name: Stopping node
  systemd:
    state: stopped
    name: "{{ node_binary_name}}-node"
  ignore_errors: yes
  notify: restart-node

- name: Delete 'keystore' and 'network' folders
  file:
    path: "{{ item }}"
    state: absent
  with_items:
  - "{{ node_home_dir }}/{{ relaychain_db_path }}/keystore"
  - "{{ node_home_dir }}/{{ relaychain_db_path }}/network"
  ignore_errors: yes
