- name: "Listing files in {{ node_home_dir }}/{{ relaychain_db_path }}/keystore" 
  find:
    paths: "{{ node_home_dir }}/{{ relaychain_db_path }}/keystore"
    file_type: file
  register: found_files

- name: print file names without path
  debug:
    msg: "{{ found_files['files'] | sort(attribute='ctime') | map(attribute='path') | map('regex_replace','^.*/(.*)$','\\1') | list }}"
