variable "instances" {}
variable "project" {}
variable "prefix" {} 
variable "module" {}
variable "roles" {}
variable "baskets" {}
variable "regions" {}
variable "disks" {}
variable "telemetry_names" {}
