variable "inventory_path" {}
variable "instances" {}
variable "project" {}
variable "prefix" {} 
variable "module" {}
variable "regions" {}
variable "disks" {}
variable "vars" {}
variable "vars_list" {}
variable "vars_nested" {}
